### ISSUE TITLE
UnhandledPromiseRejection-Error when server responds with 403

### ISSUE THREAD

**Issue by Chaphasilor** [hgouveia/node-downloader-helper#28]
I have encountered an error where a promise rejection isn't properly caught inside the module.  
It happens when the server responds with status `403`.

Here's the log:

```node
(node:29744) UnhandledPromiseRejectionWarning: Error: Response status was 403
    at ClientRequest.<anonymous> (D:\Code\NodeJS\njoy\node_modules\node-downloader-helper\dist\index.js:1:5974)
    at Object.onceWrapper (events.js:300:26)    at ClientRequest.emit (events.js:210:5) 
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)       
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)     
    at addChunk (_stream_readable.js:308:12)    at readableAddChunk (_stream_readable.js:289:11)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
(node:29744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The `.on('error')` handler is working and catching the error, but it seems like it is thrown again afterwards.  
I tried wrapping the download constructor inside a `try...catch` block but that didn't help.

Any ideas why this is happening?

**Comment by hgouveia** [comment]
Hello @Chaphasilor , this is intentional, the `.start()` returns a promise , i will resolve when the download is finished, or reject when fails to download , you can fix it just adding a catch

```
dl.start().catch((err) =>console.log('unable to download', err));
```

**Comment by Chaphasilor** [comment]
Ahhh I see, didn't think about handling `.start()`...

Thanks for the response!
