### ISSUE TITLE
CLI mode doesn't work since v1.0.14

### ISSUE THREAD

**Issue by Chaphasilor** [hgouveia/node-downloader-helper#39]
To recreate:

1. Use Node 14
2. Install `node-downloader-helper` > 1.0.13 (`npm i node-downloader-helper -g`)
3. Run `ndh . <any url>`
4. Get the following error message:

```log
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../example/helpers'
Require stack:
- ...\npm\node_modules\node-downloader-helper\bin\ndh
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (...\npm\node_modules\node-downloader-helper\bin\ndh:8:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...\\npm\\node_modules\\node-downloader-helper\\bin\\ndh'
  ]
}
```

Installing `node-downloader-helper@1.0.13` fixed the issue.

**Comment by hgouveia** [comment]
@Chaphasilor should be fixed now published in 1.0.16

**Comment by Chaphasilor** [comment]
> should be fixed now published in 1.0.16

@hgouveia hate to break it to you, but it isn't :/

![image](https://user-images.githubusercontent.com/18015147/105879646-b81c5e00-6002-11eb-8470-15c91baee810.png)

**Comment by hgouveia** [comment]
> > should be fixed now published in 1.0.16
> 
> @hgouveia hate to break it to you, but it isn't :/
> 
> ![image](https://user-images.githubusercontent.com/18015147/105879646-b81c5e00-6002-11eb-8470-15c91baee810.png)

yeap sorry i was about to write about this, for some mistake on my github actions, the package was published incomplete, i will republish as 1.0.17 and let you know

**Comment by hgouveia** [comment]
@Chaphasilor hopefully should be fine now

**Comment by Chaphasilor** [comment]
Yep. All working now :D

Thanks for the fix!
